### ISSUE TITLE
What is our maximum open files?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/leveldown-mobile#3]
We have been having problems with running out of file descriptors (we think). We thought it might be due to network connections but so far it just doesn't seem like we use all that many (we are only testing with two devices). So I was thinking about Leveldown-Mobile. In looking around the code it seems like (I'm thinking of database.cc) that maxOpenFiles is set to 1000. That seems rather high for a mobile platform. Shouldn't it be more like... I don't know... 10? 20?

Honestly I doubt if this is the cause of our file descriptor problem because we see the bug more on Android than on Wifi but Wifi actually uses the DB more (we allow more simultaneous replications) but I'm reaching at straws and 1000 is way too high. Android's limit is 1024 and we share those descriptors with network connections.

**Comment by enricogior** [comment]
From https://github.com/Level/leveldown-mobile/blob/master/README.md

  'maxOpenFiles' (number, default: 1000): The maximum number of files that LevelDB
  is allowed to have open at a time. If your data store is likely to have a large working set,
  you may increase this value to prevent file descriptor churn. To calculate the number of
  files required for your working set, divide your total data by 2MB, as each table file is a
  maximum of 2MB.

That is an option that can be passed to`leveldown#open([options, ]callback)`.
Let me know if we really need to change this since it doesn't look like an issue, since it only opens the files it needs.
